### ISSUE TITLE
Need callouts diag

### ISSUE THREAD

**Issue by peter-conalgo** [Coldcard/coldcard-web#1]
![screen shot 2018-07-30 at 9 18 19 am](https://user-images.githubusercontent.com/1482781/43399650-9f52075a-93d9-11e8-8fc8-85b89b2ef848.png)

@nvk please make something like above, except
- keep the creative (AI) files out of this repo, because otherwise they get upload to server
- just use numbers to point to stuff, so text below can refer to stuff and diag easier to make

Need
- genuine
- caution
- oled
- micro sd
- usb
- keypad (as a group?)
- OK button
- X button

Could also do the back, but probably not worth it... nothing to see there

**Comment by peter-conalgo** [comment]
- add your PNG to ./docs
- I'll write the text to go with, on a new page

**Comment by nvk** [comment]
in `docs/static/coldcard-callouts-diagram.png`

![coldcard-callouts-diagram](https://user-images.githubusercontent.com/797193/43401249-a6899da4-93dd-11e8-90f9-1215b5317214.png)

Note: the ok/X buttons didn't make sense, quite obvious. I think you should just mention them under the keyboard group.

**Comment by peter-conalgo** [comment]
- make numpad "6". oled is already "1"

**Comment by nvk** [comment]
This was already fix a few comments ago.

**Comment by peter-conalgo** [comment]
github didn't push your edit (of the comment) to my browser, looks great now

**Comment by peter-conalgo** [comment]
deployed
